### ISSUE TITLE
Creating template and building doesn't seem to be working

### ISSUE THREAD

**Issue by jordo** [godot-nim/gdext-nim#101] opened 2024-10-11 16:32 UTC
```
Jordans-M3-MacBook-Pro:game jordanschidlowsky$ gdextwiz new-extension game2
wizard new-extension*     Info: new-extension is activated 
wizard new-extension*     Info: project.godot found 
wizard new-extension*  Success: create directory nim/game2 
Jordans-M3-MacBook-Pro:game jordanschidlowsky$ gdextwiz  build-all
wizard build-all*     Info: using /Users/jordanschidlowsky/WINTERPIXEL/PROJECTS/ballz/game/project.godot 
wizard build-all*     Info: build /Users/jordanschidlowsky/WINTERPIXEL/PROJECTS/ballz/game/nim/game2/bootstrap.nim 
Hint: used config file '/opt/homebrew/Cellar/nim/2.2.0/nim/config/nim.cfg' [Conf]
Hint: used config file '/opt/homebrew/Cellar/nim/2.2.0/nim/config/config.nims' [Conf]
Hint: used config file '/Users/jordanschidlowsky/WINTERPIXEL/PROJECTS/ballz/game/nim/game2/config.nims' [Conf]
..............................................................................................................................................................................................
/Users/jordanschidlowsky/.nimble/pkgs2/gdext-0.2.0-f8d25a2473361c28332ebd98cdfd407dccd9c81c/gdext/surface/userclass.nim(83, 92) template/generic instantiation of `gdcall` from here
/Users/jordanschidlowsky/.nimble/pkgs2/gdext-0.2.0-f8d25a2473361c28332ebd98cdfd407dccd9c81c/gdext/surface/userclass.nim(84, 54) template/generic instantiation of `getOrDefault` from here
/opt/homebrew/Cellar/nim/2.2.0/nim/lib/pure/collections/tables.nim(437, 19) Error: type mismatch: got <typedesc[ClassCallVirtual]>
but expected one of:
ClassCallVirtual = proc (p_instance: ClassInstancePtr, p_args: ptr UncheckedArray[ConstTypePtr], r_ret: TypePtr){.cdecl.}
```

Thoughts?

**Comment by jordo** [comment] 2024-10-11 17:31
Hmmm, seems like it's fixed here:   https://github.com/nim-lang/Nim/pull/24265

**Comment by jordo** [comment] 2024-10-11 17:54
Compiling nim from latest 2.2.0 src, now running into this:

```
Jordans-M3-MacBook-Pro:game2 jordanschidlowsky$ gdextwiz build
wizard build*     Info: using /Users/jordanschidlowsky/WINTERPIXEL/PROJECTS/ballz/game/nim/game2/bootstrap.nim 
Hint: used config file '/Users/jordanschidlowsky/WINTERPIXEL/PROJECTS/Nim/config/nim.cfg' [Conf]
Hint: used config file '/Users/jordanschidlowsky/WINTERPIXEL/PROJECTS/Nim/config/config.nims' [Conf]
Hint: used config file '/Users/jordanschidlowsky/WINTERPIXEL/PROJECTS/ballz/game/nim/game2/config.nims' [Conf]
......................................................................................................................................................................................................
stack trace: (most recent call last)
/Users/jordanschidlowsky/.nimble/pkgs2/gdext-0.2.0-f8d25a2473361c28332ebd98cdfd407dccd9c81c/gdext/core/gdclass.nim(120, 46) Super
/Users/jordanschidlowsky/.nimble/pkgs2/gdext-0.2.0-f8d25a2473361c28332ebd98cdfd407dccd9c81c/gdext/utils/macros.nim(142, 14) super
/Users/jordanschidlowsky/WINTERPIXEL/PROJECTS/Nim/lib/pure/collections/tables.nim(381, 22) contains
/Users/jordanschidlowsky/WINTERPIXEL/PROJECTS/Nim/lib/pure/collections/tables.nim(371, 18) hasKey
/Users/jordanschidlowsky/WINTERPIXEL/PROJECTS/Nim/lib/pure/collections/hashcommon.nim(59, 12) rawGet
/Users/jordanschidlowsky/.nimble/pkgs2/gdext-0.2.0-f8d25a2473361c28332ebd98cdfd407dccd9c81c/gdext/utils/macros.nim(21, 44) hash
/Users/jordanschidlowsky/WINTERPIXEL/PROJECTS/ballz/game/nim/game2/bootstrap.nim(16, 1) template/generic instantiation of `GDExtension_EntryPoint` from here
/Users/jordanschidlowsky/.nimble/pkgs2/gdext-0.2.0-f8d25a2473361c28332ebd98cdfd407dccd9c81c/gdext/surface/init.nim(44, 70) template/generic instantiation of `gdcall` from here
/Users/jordanschidlowsky/.nimble/pkgs2/gdext-0.2.0-f8d25a2473361c28332ebd98cdfd407dccd9c81c/gdext/surface/init.nim(52, 30) template/generic instantiation of `initializeExtensionMain` from here
/Users/jordanschidlowsky/.nimble/pkgs2/gdext-0.2.0-f8d25a2473361c28332ebd98cdfd407dccd9c81c/gdext/extclasses/gdextensionmain.nim(24, 3) template/generic instantiation of `register` from here
/Users/jordanschidlowsky/.nimble/pkgs2/gdext-0.2.0-f8d25a2473361c28332ebd98cdfd407dccd9c81c/gdext/surface/userclass.nim(133, 101) template/generic instantiation of `Super` from here
/Users/jordanschidlowsky/.nimble/pkgs2/gdext-0.2.0-f8d25a2473361c28332ebd98cdfd407dccd9c81c/gdext/utils/macros.nim(21, 44) Error: node is not a symbol```

**Comment by panno8M** [comment] 2024-10-12 00:52
@jordo 
We have revised the stack traces based on the stack traces we received.
Regarding the error about `getOrDefault`, may I ask you to check the behavior, as I could not reproduce it in my Linux environment, probably because it is Mac-specific.

You can install the patched version with the following command:
```bash
nimble uninstall gdext
nimble install https://github.com/godot-nim/gdext-nim@#101-creating-template-and-building-doesnt-seem-to-be-working
```

**Comment by jordo** [comment] 2024-10-17 22:31
I got it working as well by removing that `, nil` so can confirm this should be working with nim 2.2 now.

**Comment by panno8M** [comment] 2024-10-17 23:18
Alright, thanks for your report. I close the issue with my appreciation for your contribution.

**Closed by panno8M** 2024-10-17 23:18 UTC
Labels: bug
